package app

import (
	"github.com/spf13/cobra"

	"github.com/breml/logstash-config/internal/app/lint"
)

func makeLintCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:           "lint [path ...]",
		Short:         "lint for logstash config files",
		RunE:          runLint,
		SilenceErrors: true,
	}

	cmd.Flags().Bool("auto-fix-id", false, "add an autogenerated Logstash plugin id to the configuration, if the ID is missing")

	return cmd
}

func runLint(cmd *cobra.Command, args []string) error {
	autoFixID, _ := cmd.Flags().GetBool("auto-fix-id")

	lint := lint.New(autoFixID)
	return lint.Run(args)
}
