---

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ "stable", "oldstable", "1.x" ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    -
      name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    -
      name: Checkout code
      uses: actions/checkout@v4

    -
      name: Build
      run: go build ./...

    -
      name: Test
      run: go test -v -cover ./...
